frase= "Curso em video Python"
print(frase[9::3])
print(frase.count("o",0,21))
print(frase.find("deo"))
print(frase.replace("Python", "Android"))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
juntos="-".join(frase)
print(juntos)
print(len(frase.strip()))
print(frase.lower().find("video"))
print(frase.split())
dividido= frase.split()
print(dividido[0])
# frase = "   Aprenda Python  "
# print(frase.strip())
# print(frase.rstrip())
# print(frase.lstrip())