a = input('Digite algo')
print("o tipo primitivo é", type(a))
print('só tem espaços?', a.isspace())
print('É um numero?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('é alfanumérico?', a.isalnum())
print('Está em minuscula?', a.isupper())
print('Está em maiuscula', a.islower()
)